services:
  db:
    image: postgres:16
    container_name: inv-postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory -d inventorydb"]
      interval: 5s
      timeout: 5s
      retries: 10
